language: php
sudo: false
install: composer install

addons:
  apt:
    packages:
      - nginx

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

matrix:
  allow_failures:
    - php: 7.3

before_script:
  - bash tests/bin/install.sh woocommerce_test root '' localhost latest
  - git clone https://github.com/woocommerce/woocommerce.git

script: b2binpay-payments-for-woocommerce/includes/bin/phpunit

after_success:
- travis_retry php b2binpay-payments-for-woocommerce/includes/bin/php-coveralls
